# Generated by Django 5.0.1 on 2024-03-18 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Enter the category name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Enter the category name"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="pdf",
            field=models.FileField(blank=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="companystructure",
            name="pdf",
            field=models.FileField(blank=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="category",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.category",
                verbose_name="Enter the category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companystructure",
            name="category",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.categorystructure",
                verbose_name="Enter the category",
            ),
            preserve_default=False,
        ),
    ]
